FROM node:20

# netcat-openbsd를 써야 netcat이 깔립니다.
RUN apt-get update && apt-get install -y netcat-openbsd

WORKDIR /

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 8000

CMD ["npm", "start"]